db:
  production:
    adapter:  mysql2
    host:     localhost
    username: hoge
    password: hoge
    database: hoge

  development:
    adapter:  mysql2
    host:     localhost
    username: <%= ENV['DEV_DATABASE_USERNAME'] %>
    password: <%= ENV['DEV_DATABASE_PASSWORD'] %>
    database: <%= ENV['DEV_DATABASE_NAME']%>
